version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: "insuratradeflow-app-v1"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "insuratradeflow-mysql-v1:3306", "--", "java", "-jar", "demo-1.0-SNAPSHOT.jar"]
    networks:
      - app-network
    environment:
      - DATABASE_HOST=insuratradeflow-mysql-v1
      - DATABASE_PORT=3306

  mysql:
    image: mysql:8.0
    container_name: "insuratradeflow-mysql-v1"
    restart: always
    # command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "InsuraTradeFlow"
      MYSQL_USER: "InsuraTradeFlowUser"
      MYSQL_PASSWORD: "InsuraTradeFlowPassword"
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge