version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: insuratradeflow-mysql-v1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: InsuraTradeFlow
      MYSQL_USER: InsuraTradeFlowUser
      MYSQL_PASSWORD: InsuraTradeFlowPassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build: .
    container_name: insuratradeflow-app-v1
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/InsuraTradeFlow
      DATABASE_USER: InsuraTradeFlowUser
      DATABASE_PASSWORD: InsuraTradeFlowPassword
    restart: on-failure